name: Build AllTrans Debug Simple

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          
      - name: Build Debug APK
        run: |
          echo "sdk.dir=/usr/local/lib/android/sdk" > local.properties
          ./gradlew :app:assembleDebug --no-daemon
        
      - uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk